name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Publish GUI
        run: dotnet publish -p:PublishSingleFile=true --self-contained true -r win-x64 -c Release src/StarBreaker/StarBreaker.csproj

      - name: Publish CLI
        run: dotnet publish -p:PublishSingleFile=true --self-contained true -r win-x64 -c Release src/StarBreaker.Cli/StarBreaker.Cli.csproj

      - name: Upload GUI
        uses: actions/upload-artifact@v4
        with:
          name: StarBreaker
          path: | 
            src/StarBreaker/bin/Release/net9.0/win-x64/publish
            !**/*.pdb

      - name: Upload CLI
        uses: actions/upload-artifact@v4
        with:
          name: StarBreaker.Cli
          path: |
            src/StarBreaker.Cli/bin/Release/net9.0/win-x64/publish
            !**/*.pdb