name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Publish
        run: dotnet publish src

      - name: Upload GUI
        uses: actions/upload-artifact@v4
        with:
          name: StarBreaker
          path: src/StarBreaker/bin/Release/net9.0/win-x64/publish

      - name: Upload CLI
        uses: actions/upload-artifact@v4
        with:
          name: StarBreaker.Cli
          path: src/StarBreaker.Cli/bin/Release/net9.0/win-x64/publish